
version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
   
    steps:
      - checkout
      - run:
          name: Install dependencies
          # This assumes pytest is installed via the install-package step above
          command: |
            make install
         
      - run:
          name: Run lint
          # This assumes pytest is installed via the install-package step above
          command: |
            make lint


workflows:
  sample: 
    jobs:
      - build-and-test